SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `sgc` DEFAULT CHARACTER SET utf8 ;
USE `sgc` ;

-- -----------------------------------------------------
-- Table `sgc`.`ESTADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`ESTADOS` (
  `ESTA_ID` INT NOT NULL AUTO_INCREMENT,
  `ESTA_NOME` VARCHAR(45) NOT NULL,
  `ESTA_UF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ESTA_ID`))
ENGINE = InnoDB
PACK_KEYS = Default;


-- -----------------------------------------------------
-- Table `sgc`.`CIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`CIDADES` (
  `CIDA_ID` INT NOT NULL AUTO_INCREMENT,
  `CIDA_NOME` VARCHAR(45) NOT NULL,
  `ESTA_ID` INT NOT NULL,
  PRIMARY KEY (`CIDA_ID`),
  INDEX `fk_CIDADES_ESTADOS1_idx` (`ESTA_ID` ASC),
  CONSTRAINT `fk_CIDADES_ESTADOS1`
    FOREIGN KEY (`ESTA_ID`)
    REFERENCES `sgc`.`ESTADOS` (`ESTA_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`BAIRROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`BAIRROS` (
  `BAIRRO_ID` INT NOT NULL AUTO_INCREMENT,
  `BAIRRO_NOME` VARCHAR(45) NULL,
  `CIDA_ID` INT NOT NULL,
  PRIMARY KEY (`BAIRRO_ID`),
  INDEX `fk_BAIRROS_CIDADES1_idx` (`CIDA_ID` ASC),
  CONSTRAINT `fk_BAIRROS_CIDADES1`
    FOREIGN KEY (`CIDA_ID`)
    REFERENCES `sgc`.`CIDADES` (`CIDA_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`RUAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`RUAS` (
  `RUA_ID` INT NOT NULL AUTO_INCREMENT,
  `RUA_NOME` VARCHAR(45) NULL,
  `RUA_CEP` VARCHAR(45) NULL,
  `BAIRRO_ID` INT NOT NULL,
  PRIMARY KEY (`RUA_ID`),
  INDEX `fk_RUA_BAIRROS1_idx` (`BAIRRO_ID` ASC),
  CONSTRAINT `fk_RUA_BAIRROS1`
    FOREIGN KEY (`BAIRRO_ID`)
    REFERENCES `sgc`.`BAIRROS` (`BAIRRO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`ENDERECOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`ENDERECOS` (
  `END_ID` INT NOT NULL AUTO_INCREMENT,
  `END_NUMERO` INT NULL,
  `END_REFERENCIA` VARCHAR(45) NULL,
  `RUA_ID` INT NOT NULL,
  PRIMARY KEY (`END_ID`),
  INDEX `fk_ENDERECOS_RUA1_idx` (`RUA_ID` ASC),
  CONSTRAINT `fk_ENDERECOS_RUA1`
    FOREIGN KEY (`RUA_ID`)
    REFERENCES `sgc`.`RUAS` (`RUA_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`PESSOAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`PESSOAS` (
  `PES_ID` INT NOT NULL AUTO_INCREMENT,
  `PES_NOME` TEXT NOT NULL,
  `PES_CPF_CNPJ` VARCHAR(18) NOT NULL,
  `PES_NOME_PAI` TEXT NULL,
  `PES_NOME_MAE` TEXT NULL,
  `PES_NASC_DATA` DATE NULL,
  `PES_FONE` VARCHAR(14) NULL,
  `PES_CEL1` VARCHAR(14) NOT NULL,
  `PES_CEL2` VARCHAR(14) NULL,
  `END_ID` INT NOT NULL,
  `PES_TIPO` ENUM('f','j') NOT NULL COMMENT 'f = fisica\nj = juridica',
  `PES_ESTATUS` ENUM('a','d') NULL,
  `PES_DATA` DATETIME NOT NULL,
  `PES_EMAIL` VARCHAR(120) NULL,
  PRIMARY KEY (`PES_ID`),
  INDEX `fk_PESSOAS_ENDERECOS1_idx` (`END_ID` ASC),
  UNIQUE INDEX `PES_CPF_CNPJ_UNIQUE` (`PES_CPF_CNPJ` ASC),
  CONSTRAINT `fk_PESSOAS_ENDERECOS`
    FOREIGN KEY (`END_ID`)
    REFERENCES `sgc`.`ENDERECOS` (`END_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
ROW_FORMAT = Default;


-- -----------------------------------------------------
-- Table `sgc`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`CATEGORIAS` (
  `CATE_ID` INT NOT NULL AUTO_INCREMENT,
  `CATE_NOME` VARCHAR(20) NOT NULL,
  `CATE_DESCRIC` TEXT NULL,
  `CATE_IMG` VARCHAR(20) NULL,
  `CATE_ESTATUS` ENUM('a','d') NULL,
  PRIMARY KEY (`CATE_ID`),
  UNIQUE INDEX `CATE_NOME_UNIQUE` (`CATE_NOME` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`MEDIDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`MEDIDAS` (
  `MEDI_ID` INT NOT NULL AUTO_INCREMENT,
  `MEDI_NOME` VARCHAR(45) NOT NULL,
  `MEDI_SIGLA` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`MEDI_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`PRODUTOS` (
  `PRO_ID` INT NOT NULL AUTO_INCREMENT,
  `PRO_DESCRICAO` VARCHAR(100) NOT NULL,
  `PRO_CARAC_TEC` TEXT NULL,
  `CATE_ID` INT NOT NULL,
  `MEDI_ID` INT NOT NULL,
  `PRO_IMG` VARCHAR(10) NULL,
  `PRO_PESO` DECIMAL(10,3) NULL,
  `PRO_TIPO` ENUM('p','s') NOT NULL,
  `PRO_ESTATUS` ENUM('d','a') NOT NULL,
  PRIMARY KEY (`PRO_ID`),
  INDEX `fk_PRODUTOS_CATEGORIA1_idx` (`CATE_ID` ASC),
  UNIQUE INDEX `PRO_DESCRICAO_UNIQUE` (`PRO_DESCRICAO` ASC),
  INDEX `fk_PRODUTOS_UNIDADE1_idx` (`MEDI_ID` ASC),
  CONSTRAINT `fk_PRODUTOS_CATEGORIA`
    FOREIGN KEY (`CATE_ID`)
    REFERENCES `sgc`.`CATEGORIAS` (`CATE_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PRODUTOS_UNIDADE`
    FOREIGN KEY (`MEDI_ID`)
    REFERENCES `sgc`.`MEDIDAS` (`MEDI_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`ESTOQUES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`ESTOQUES` (
  `ESTOQ_ID` INT NOT NULL AUTO_INCREMENT,
  `PRO_ID` INT NOT NULL,
  `ESTOQ_ATUAL` DECIMAL(10,2) NULL,
  `ESTOQ_MIN` DECIMAL(10,2) NULL,
  `ESTOQ_CUSTO` DECIMAL(10,2) NULL,
  `ESTOQ_PRECO` DECIMAL(10,2) NOT NULL,
  `ESTOQ_ENTRA` DATETIME NULL,
  PRIMARY KEY (`ESTOQ_ID`),
  INDEX `fk_ESTOQUES_PRODUTOS1_idx` (`PRO_ID` ASC),
  UNIQUE INDEX `PRO_ID_UNIQUE` (`PRO_ID` ASC),
  CONSTRAINT `fk_ESTOQUES_PRODUTOS1`
    FOREIGN KEY (`PRO_ID`)
    REFERENCES `sgc`.`PRODUTOS` (`PRO_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`CARGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`CARGOS` (
  `CARG_ID` INT NOT NULL AUTO_INCREMENT,
  `CARG_NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CARG_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`USUARIOS` (
  `USUARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `CARG_ID` INT NOT NULL,
  `PES_ID` INT NOT NULL,
  `USUARIO_APELIDO` VARCHAR(45) NOT NULL,
  `USUARIO_LOGIN` VARCHAR(45) NOT NULL,
  `USUARIO_SENHA` TEXT NOT NULL,
  `USUARIO_ESTATUS` ENUM('a','d') NOT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  INDEX `fk_USUARIO_CARGOS1_idx` (`CARG_ID` ASC),
  INDEX `fk_USUARIO_PESSOAS1_idx` (`PES_ID` ASC),
  UNIQUE INDEX `PES_ID_UNIQUE` (`PES_ID` ASC),
  UNIQUE INDEX `USUARIO_LOGIN_UNIQUE` (`USUARIO_LOGIN` ASC),
  CONSTRAINT `fk_USUARIO_CARGOS1`
    FOREIGN KEY (`CARG_ID`)
    REFERENCES `sgc`.`CARGOS` (`CARG_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USUARIO_PESSOAS1`
    FOREIGN KEY (`PES_ID`)
    REFERENCES `sgc`.`PESSOAS` (`PES_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`FORMA_PG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`FORMA_PG` (
  `FPG_ID` INT NOT NULL AUTO_INCREMENT,
  `FPG_DESCR` VARCHAR(30) NOT NULL,
  `FPG_PARCE` INT NOT NULL,
  `FPG_AJUSTE` DECIMAL(3,2) NOT NULL,
  `FPG_STATUS` ENUM('a','d') NOT NULL COMMENT 'A = ativo\nD = desativo',
  PRIMARY KEY (`FPG_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`PEDIDOS` (
  `PEDIDO_ID` INT NOT NULL AUTO_INCREMENT,
  `PES_ID` INT NULL,
  `USUARIO_ID` INT NOT NULL,
  `PEDIDO_ESTATUS` ENUM('1','2','3','4','5') NOT NULL COMMENT '1 = EM ABERTA\n2 = AGUARDANDO PAGAMENTO\n3 = ENVIADO\n4 = CONCLUIDO\n5 = CANCELADA',
  `PEDIDO_TIPO` ENUM('v','c') NOT NULL,
  `PEDIDO_LOCAL` ENUM('l','i') NOT NULL COMMENT 'l = local\ni = internet',
  `PEDIDO_OBS` TEXT NULL,
  `PEDIDO_N_DOC` VARCHAR(45) NULL,
  `PEDIDO_IMPOSTO` DECIMAL(10,2) NULL COMMENT 'IMPOSTO',
  `PEDIDO_FRETE` DECIMAL(10,2) NULL COMMENT 'FRETE',
  `PEDIDO_DATA` DATETIME NOT NULL,
  `PG_FPG_ID` INT NULL DEFAULT 1,
  `PEDIDO_NPARC` INT NULL DEFAULT 1,
  PRIMARY KEY (`PEDIDO_ID`),
  INDEX `fk_VENDAS_PESSOAS1_idx` (`PES_ID` ASC),
  INDEX `fk_VENDAS_USUARIO1_idx` (`USUARIO_ID` ASC),
  INDEX `fk_PEDIDOS_FORMA_PG1_idx` (`PG_FPG_ID` ASC),
  CONSTRAINT `fk_VENDAS_PESSOAS`
    FOREIGN KEY (`PES_ID`)
    REFERENCES `sgc`.`PESSOAS` (`PES_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VENDAS_USUARIO`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `sgc`.`USUARIOS` (`USUARIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PEDIDOS_FORMA_PG1`
    FOREIGN KEY (`PG_FPG_ID`)
    REFERENCES `sgc`.`FORMA_PG` (`FPG_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`ORDEM_SERV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`ORDEM_SERV` (
  `OS_ID` INT NOT NULL AUTO_INCREMENT,
  `PES_ID` INT NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  `OS_EQUIPAMENT` TEXT NOT NULL COMMENT 'DADOS DO EQUIPAMENTO DO CLIENTE',
  `OS_DSC_DEFEITO` TEXT NOT NULL,
  `OS_DSC_SOLUC` TEXT NULL,
  `OS_DSC_PENDENT` TEXT NULL,
  `OS_DATA_ENT` DATETIME NOT NULL,
  `OS_DATA_SAI` DATETIME NULL,
  `OS_OBSERVACAO` TEXT NULL,
  `OS_DESCONTO` DECIMAL(10,2) NULL,
  `FPG_ID` INT NULL,
  `OS_NPARC` INT NULL,
  `OS_ESTATUS` ENUM('1','2','3','4') NOT NULL COMMENT 'OS_ESTATUS PODE SER\n1=EM ABERTO\n2=PENDENTE\n3=CONCLUIDO\n4=ESTREGUE',
  PRIMARY KEY (`OS_ID`),
  INDEX `fk_ORDEM_SERV_PESSOAS1_idx` (`PES_ID` ASC),
  INDEX `fk_ORDEM_SERV_USUARIO1_idx` (`USUARIO_ID` ASC),
  INDEX `fk_ORDEM_SERV_FORMA_PG1_idx` (`FPG_ID` ASC),
  CONSTRAINT `fk_ORDEM_SERV_PESSOAS1`
    FOREIGN KEY (`PES_ID`)
    REFERENCES `sgc`.`PESSOAS` (`PES_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ORDEM_SERV_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `sgc`.`USUARIOS` (`USUARIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ORDEM_SERV_FORMA_PG1`
    FOREIGN KEY (`FPG_ID`)
    REFERENCES `sgc`.`FORMA_PG` (`FPG_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`LISTA_PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`LISTA_PRODUTOS` (
  `LIST_PED_ID` INT NOT NULL AUTO_INCREMENT,
  `PEDIDO_ID` INT NULL,
  `ESTOQ_ID` INT NOT NULL,
  `OS_ID` INT NULL,
  `LIST_PED_QNT` DECIMAL(10,2) NOT NULL,
  `LIST_PED_PRECO` DECIMAL(10,2) NULL,
  `LIST_PED_COMP` DECIMAL(10,2) NULL,
  `LIST_PED_DESC` DECIMAL(10,2) NULL COMMENT 'DESCONTO',
  PRIMARY KEY (`LIST_PED_ID`),
  INDEX `fk_LISTA_PRODUTO_ESTOQUE1_idx` (`ESTOQ_ID` ASC),
  INDEX `fk_LISTA_PEDIDO_PEDIDO1_idx` (`PEDIDO_ID` ASC),
  INDEX `fk_LISTA_PEDIDO_ORDEM_SERV1_idx` (`OS_ID` ASC),
  CONSTRAINT `fk_LISTA_PRODUTO_ESTOQUE1`
    FOREIGN KEY (`ESTOQ_ID`)
    REFERENCES `sgc`.`ESTOQUES` (`ESTOQ_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LISTA_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_ID`)
    REFERENCES `sgc`.`PEDIDOS` (`PEDIDO_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LISTA_PEDIDO_ORDEM_SERV1`
    FOREIGN KEY (`OS_ID`)
    REFERENCES `sgc`.`ORDEM_SERV` (`OS_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`AVARIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`AVARIAS` (
  `AVA_ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` INT NOT NULL,
  `ESTOQ_ID` INT NOT NULL,
  `AVA_QNT` INT NOT NULL,
  `AVA_MOTIVO` TEXT NOT NULL,
  `AVA_DATA` DATE NOT NULL,
  PRIMARY KEY (`AVA_ID`),
  INDEX `fk_AVARIA_USUARIO1_idx` (`USUARIO_ID` ASC),
  INDEX `fk_AVARIA_ESTOQUE1_idx` (`ESTOQ_ID` ASC),
  CONSTRAINT `fk_AVARIA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `sgc`.`USUARIOS` (`USUARIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AVARIA_ESTOQUE1`
    FOREIGN KEY (`ESTOQ_ID`)
    REFERENCES `sgc`.`ESTOQUES` (`ESTOQ_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`METODOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`METODOS` (
  `METOD_ID` INT NOT NULL AUTO_INCREMENT,
  `METOD_CLASS` VARCHAR(45) NOT NULL,
  `METOD_METODO` VARCHAR(45) NOT NULL,
  `METOD_PRIVADO` TINYINT(1) NOT NULL,
  `METOD_DESCR` VARCHAR(45) NULL COMMENT 'Descrição do metodo ou informação.',
  PRIMARY KEY (`METOD_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`PERMISSOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`PERMISSOES` (
  `PERM_ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` INT NOT NULL,
  `METOD_ID` INT NOT NULL,
  PRIMARY KEY (`PERM_ID`),
  INDEX `fk_USUARIO_has_PERMICOES_PERMICOES1_idx` (`METOD_ID` ASC),
  INDEX `fk_USUARIO_has_PERMICOES_USUARIO1_idx` (`USUARIO_ID` ASC),
  CONSTRAINT `fk_USUARIO_has_PERMICOES_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `sgc`.`USUARIOS` (`USUARIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USUARIO_has_PERMICOES_PERMICOES1`
    FOREIGN KEY (`METOD_ID`)
    REFERENCES `sgc`.`METODOS` (`METOD_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`LOG_ACESSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`LOG_ACESSOS` (
  `LOG_ACESS_ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` INT NOT NULL,
  `METOD_ID` INT NULL,
  `LOG_ACESS_IP` VARCHAR(40) NOT NULL,
  `LOG_ACESS_DATA` DATETIME NOT NULL,
  `LOG_ACESS_MSN` VARCHAR(45) NULL,
  PRIMARY KEY (`LOG_ACESS_ID`),
  INDEX `fk_LOG_ACESSO_USUARIO1_idx` (`USUARIO_ID` ASC),
  INDEX `fk_LOG_ACESSOS_METODOS1_idx` (`METOD_ID` ASC),
  CONSTRAINT `fk_LOG_ACESSO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `sgc`.`USUARIOS` (`USUARIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LOG_ACESSOS_METODOS1`
    FOREIGN KEY (`METOD_ID`)
    REFERENCES `sgc`.`METODOS` (`METOD_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`EMPRESAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`EMPRESAS` (
  `EMPRE_ID` INT NOT NULL AUTO_INCREMENT,
  `EMPRE_RAZAO` VARCHAR(60) NOT NULL,
  `EMPRE_CNPJ` VARCHAR(18) NOT NULL,
  `EMPRE_ESCR_ESTADUAL` INT NOT NULL,
  `EMPRE_FONE` VARCHAR(14) NOT NULL,
  `EMPRE_FAX` VARCHAR(14) NULL,
  `EMPRE_EMAIL` VARCHAR(120) NOT NULL,
  `EMPRE_SITE` VARCHAR(100) NULL,
  `EMPRE_NOME` VARCHAR(45) NOT NULL,
  `EMPRE_SLOGAN` VARCHAR(60) NOT NULL,
  `END_ID` INT NULL,
  PRIMARY KEY (`EMPRE_ID`),
  INDEX `fk_EMPRESA_ENDERECOS1_idx` (`END_ID` ASC),
  CONSTRAINT `fk_EMPRESA_ENDERECOS1`
    FOREIGN KEY (`END_ID`)
    REFERENCES `sgc`.`ENDERECOS` (`END_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`COMPRAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`COMPRAS` (
  `COMP_ID` INT NOT NULL AUTO_INCREMENT,
  `ESTOQ_ID` INT NOT NULL,
  `PEDIDO_ID` INT NOT NULL,
  `COMP_DATA` DATETIME NOT NULL,
  PRIMARY KEY (`COMP_ID`),
  INDEX `fk_COMPRAS_ESTOQUES1_idx` (`ESTOQ_ID` ASC),
  INDEX `fk_COMPRAS_PEDIDOS1_idx` (`PEDIDO_ID` ASC),
  CONSTRAINT `fk_COMPRAS_ESTOQUES1`
    FOREIGN KEY (`ESTOQ_ID`)
    REFERENCES `sgc`.`ESTOQUES` (`ESTOQ_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_COMPRAS_PEDIDOS1`
    FOREIGN KEY (`PEDIDO_ID`)
    REFERENCES `sgc`.`PEDIDOS` (`PEDIDO_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`DESPESA_RECEITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`DESPESA_RECEITA` (
  `DESREC_ID` INT NOT NULL AUTO_INCREMENT,
  `PEDIDO_ID` INT NULL,
  `OS_ID` INT NULL,
  `PES_ID` INT NULL COMMENT 'Somente para adição avulsa.',
  `DESREC_NATUREZA` ENUM('1','2') NOT NULL COMMENT '1 - RECEITA\n2 - DESPESA',
  `DESREC_DESCR` VARCHAR(45) NULL,
  `DESREC_VALOR` DECIMAL(10,2) NOT NULL,
  `DESREC_VECIMENTO` DATE NOT NULL,
  `DESCRE_DATA_PG` DATETIME NULL,
  `DESCRE_ESTATUS` ENUM('ab','pg','cn') NOT NULL COMMENT 'AB = aberta\nPG = Pago\nCN = Canselado',
  PRIMARY KEY (`DESREC_ID`),
  INDEX `fk_DESPESA/RECEITA_PEDIDOS1_idx` (`PEDIDO_ID` ASC),
  INDEX `fk_DESPESA_RECEITA_ORDEM_SERV1_idx` (`OS_ID` ASC),
  INDEX `fk_DESPESA_RECEITA_PESSOAS1_idx` (`PES_ID` ASC),
  CONSTRAINT `fk_DESPESA_RECEITA_PEDIDOS1`
    FOREIGN KEY (`PEDIDO_ID`)
    REFERENCES `sgc`.`PEDIDOS` (`PEDIDO_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DESPESA_RECEITA_ORDEM_SERV1`
    FOREIGN KEY (`OS_ID`)
    REFERENCES `sgc`.`ORDEM_SERV` (`OS_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DESPESA_RECEITA_PESSOAS1`
    FOREIGN KEY (`PES_ID`)
    REFERENCES `sgc`.`PESSOAS` (`PES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`HISTORICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`HISTORICO` (
  `HISTORICO_ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` INT NOT NULL,
  `DESREC_ID` INT NULL,
  `PEDIDO_ID` INT NULL,
  `OS_ID` INT NULL,
  `ESTOQ_ID` INT NULL,
  `HISTORICO_CMD` VARCHAR(30) NOT NULL,
  `HISTORICO_DATA` DATETIME NOT NULL,
  PRIMARY KEY (`HISTORICO_ID`),
  INDEX `fk_HISTORICO_DESPESA_RECEITA2_idx` (`DESREC_ID` ASC),
  INDEX `fk_HISTORICO_ORDEM_SERV2_idx` (`OS_ID` ASC),
  INDEX `fk_HISTORICO_ESTOQUES2_idx` (`ESTOQ_ID` ASC),
  INDEX `fk_HISTORICO_PEDIDOS1_idx` (`PEDIDO_ID` ASC),
  INDEX `fk_HISTORICO_USUARIOS1_idx` (`USUARIO_ID` ASC),
  CONSTRAINT `fk_HISTORICO_DESPESA_RECEITA2`
    FOREIGN KEY (`DESREC_ID`)
    REFERENCES `sgc`.`DESPESA_RECEITA` (`DESREC_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HISTORICO_ORDEM_SERV2`
    FOREIGN KEY (`OS_ID`)
    REFERENCES `sgc`.`ORDEM_SERV` (`OS_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HISTORICO_ESTOQUES2`
    FOREIGN KEY (`ESTOQ_ID`)
    REFERENCES `sgc`.`ESTOQUES` (`ESTOQ_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HISTORICO_PEDIDOS1`
    FOREIGN KEY (`PEDIDO_ID`)
    REFERENCES `sgc`.`PEDIDOS` (`PEDIDO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HISTORICO_USUARIOS1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `sgc`.`USUARIOS` (`USUARIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgc`.`PRODUTO_IMG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgc`.`PRODUTO_IMG` (
  `PROIMG_ID` INT NOT NULL AUTO_INCREMENT,
  `PROIMG_NOME` VARCHAR(45) NOT NULL,
  `PRO_ID` INT NOT NULL,
  PRIMARY KEY (`PROIMG_ID`),
  INDEX `fk_PRODUTO_IMG_PRODUTOS1_idx` (`PRO_ID` ASC),
  CONSTRAINT `fk_PRODUTO_IMG_PRODUTOS1`
    FOREIGN KEY (`PRO_ID`)
    REFERENCES `sgc`.`PRODUTOS` (`PRO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
