SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `sgc`.`LISTA_PRODUTOS` 
ADD COLUMN `LIST_PED_STATUS` ENUM('e','a') NULL DEFAULT NULL COMMENT ' /* comment truncated */ /*E = entregue
A = Aguardando*/' AFTER `LIST_PED_COMP`;

ALTER TABLE `sgc`.`FORMA_PG` 
CHANGE COLUMN `FPG_QNT` `FPG_PARCE` INT(11) NOT NULL ,
ADD COLUMN `FPG_AJUSTE` INT(11) NOT NULL AFTER `FPG_PARCE`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
